[package]
name = "walrs_acl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walrs_graph = { path = '../graph' }
serde = "1.0.103"
serde_json = "1.0.80"
serde_derive = "1.0.103"

[dev-dependencies]
rand = "0.8"
actix-web = "4"
tokio = { version = "1", features = ["full"] }

[[example]]
name = "benchmark_extensive_acl"
path = "benchmark/benchmark_extensive_acl.rs"

[[example]]
name = "benchmark_actix_middleware"
path = "benchmark/benchmark_actix_middleware.rs"
