[package]
name = "walrs"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
profiler = true

[dependencies]
ammonia = "3.3.1"
walrs_acl = { path = 'acl' }
walrs_graph = { path = 'graph' }
walrs_inputfilter = { path = "inputfilter" }
walrs_navigation = { path = "navigation" }

[workspace]
members = [
    "acl", 
    "digraph",
    "graph",
    "inputfilter",
    "navigation"
]
