[package]
name = "walrs_validation"
version = "0.1.0"
authors = ["Ely De La Cruz <elycruz@elycruz.com>"]
edition = "2024"
description = "Composable validation rules for input validation"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml"]

[features]
default = ["serde_json_bridge"]
serde_json_bridge = ["dep:serde_json"]

[dependencies]
indexmap = { version = "2", features = ["serde"] }
regex = "1.3.1"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = { version = "1.0.82", optional = true }
thiserror = "1.0"

[dev-dependencies]
serde_json = "1.0.82"

