[package]
name = "walrs_validation"
version = "0.1.0"
authors = ["Ely De La Cruz <elycruz@elycruz.com>"]
edition = "2024"
description = "Validator structs for input validation"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml"]

[features]
default = []
fn_traits = []
debug_closure_helpers = []
nightly = ["fn_traits", "debug_closure_helpers"]

[dependencies]
derive_builder = "0.13.0"
regex = "1.3.1"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "validator_benchmarks"
harness = false
